### ISSUE TITLE
Show the logo in the Slack/Twitter unfurl

### ISSUE THREAD

**Issue by gabebw** [hotline-webring/hotline-webring#185]
We should set the `twitter:image` `<meta>` tag: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

**Comment by gabebw** [comment]
@edwardloveall Do you have an image of the logo that you could attach here?

**Comment by edwardloveall** [comment]
I have dreams to redo this one day, but I'll resist the temptation of letting perfect stand in the way of good.

![Hotline Webring no background](https://user-images.githubusercontent.com/49549/59545946-460e0880-8ef4-11e9-9da7-b833cd913e58.png)

**Comment by gabebw** [comment]
@edwardloveall Unfortunately that beautiful (IMO perfect) logo gets a bit squished on twitter:

<img width="515" alt="Card Validator | Twitter Developers 2019-06-14 20-12-19" src="https://user-images.githubusercontent.com/257678/59546359-bb6fde00-8ee0-11e9-90bf-ec8a29bc7d9e.png">

Do you have the "HL WR" version that we put on our stickers?
